# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: namespace/events.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'namespace/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from namespace import types_pb2 as namespace_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16namespace/events.proto\x12\tnamespace\x1a\x15namespace/types.proto\"\xda\x01\n\rFolderChanged\x12\x1b\n\tfolder_id\x18\x01 \x01(\tR\x08\x66olderId\x12\x16\n\x06reload\x18\x02 \x01(\x08R\x06reload\x12#\n\rremoved_items\x18\x03 \x03(\tR\x0cremovedItems\x12\x36\n\x0bnew_folders\x18\x04 \x03(\x0b\x32\x15.namespace.FolderInfoR\nnewFolders\x12\x37\n\rnew_variables\x18\x05 \x03(\x0b\x32\x12.namespace.VarInfoR\x0cnewVariables\"\xcb\x01\n\x0eVarMetaChanged\x12\x15\n\x06var_id\x18\x01 \x01(\tR\x05varId\x12\x17\n\x04unit\x18\x02 \x01(\tH\x00R\x04unit\x88\x01\x01\x12\x15\n\x03min\x18\x03 \x01(\x01H\x01R\x03min\x88\x01\x01\x12\x15\n\x03max\x18\x04 \x01(\x01H\x02R\x03max\x88\x01\x01\x12\x18\n\x07options\x18\x05 \x03(\tR\x07options\x12\x1c\n\x07max_len\x18\x06 \x01(\x04H\x03R\x06maxLen\x88\x01\x01\x42\x07\n\x05_unitB\x06\n\x04_minB\x06\n\x04_maxB\n\n\x08_max_len\"\xa9\x01\n\x0bTreeChanged\x12J\n\x14\x66older_changed_event\x18\x01 \x03(\x0b\x32\x18.namespace.FolderChangedR\x12\x66olderChangedEvent\x12N\n\x16var_meta_changed_event\x18\x02 \x03(\x0b\x32\x19.namespace.VarMetaChangedR\x13varMetaChangedEvent\"\x8a\x01\n\x05\x45vent\x12\x39\n\x0cvar_value_ev\x18\x01 \x01(\x0b\x32\x15.namespace.VarIdValueH\x00R\nvarValueEv\x12@\n\x0ftree_changed_ev\x18\x02 \x01(\x0b\x32\x16.namespace.TreeChangedH\x00R\rtreeChangedEvB\x04\n\x02\x65v\"6\n\nEventBatch\x12(\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x10.namespace.EventR\x06\x65ventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'namespace.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLDERCHANGED']._serialized_start=61
  _globals['_FOLDERCHANGED']._serialized_end=279
  _globals['_VARMETACHANGED']._serialized_start=282
  _globals['_VARMETACHANGED']._serialized_end=485
  _globals['_TREECHANGED']._serialized_start=488
  _globals['_TREECHANGED']._serialized_end=657
  _globals['_EVENT']._serialized_start=660
  _globals['_EVENT']._serialized_end=798
  _globals['_EVENTBATCH']._serialized_start=800
  _globals['_EVENTBATCH']._serialized_end=854
# @@protoc_insertion_point(module_scope)
